[package]
name        = "godot-qengine"
description = "Godot 4.5 GDExtension: AudioEffectQEngine and QEngineDetectorNode for guitar pitch detection"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[lib]
# Compile as a GDExtension dynamic library.
crate-type = ["cdylib"]

[dependencies]
godot         = { version = "0.5.2", features = ["api-4-5", "experimental-threads", "__codegen-full"] }
qengine-core  = { path = "../qengine-core" }
qengine-sys   = { path = "../qengine-sys" }
rtrb          = "0.3"
