[package]
name        = "qengine-sys"
description = "Low-level FFI bindings to the cycfi/Q C++ pitch-detection library"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
links = "q_bridge"

[lib]
name = "qengine_sys"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
approx = "0.5"
